<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

La tasa de éxito de un lanzamiento puede depender de muchos factores, como la masa de la carga útil, el tipo de órbita, etc. También puede depender de la ubicación y la proximidad de la plataforma de lanzamiento, es decir, la posición inicial de la trayectoria del cohete. Encontrar la ubicación óptima para construir una plataforma de lanzamiento implica sin duda muchos factores, y esperamos poder descubrir algunos de ellos analizando las ubicaciones de las plataformas de lanzamiento existentes.

En los laboratorios anteriores de análisis exploratorio de datos, visualizaste el conjunto de datos de lanzamientos de SpaceX usando `matplotlib` y `seaborn`, y descubriste algunas correlaciones preliminares entre el sitio de lanzamiento y las tasas de éxito. En este laboratorio, realizarás análisis visuales más interactivos usando `Folium`.

## Objectivos

Este laboratorio incluye las siguientes tareas:

* **TAREA 1:** Marca todos los sitios de lanzamiento en un mapa.
* **TAREA 2:** Marca los lanzamientos exitosos y fallidos para cada sitio en el mapa.
* **TAREA 3:** Calcula las distancias entre un sitio de lanzamiento y sus proximidades.

Tras completar estas tareas, podrás identificar patrones geográficos en los sitios de lanzamiento.

Let's first import required Python packages for this lab:

In [34]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [35]:
import folium
from folium.features import DivIcon
import pandas as pd

In [36]:
# Importar el plugin folium MarkerCluster
from folium.plugins import MarkerCluster
# Importar el plugin folium MousePosition
from folium.plugins import MousePosition
# Importar el complemento Folium DivIcon
from folium.features import DivIcon

Si necesita refrescar su memoria sobre el folium, puede descargar y consultar este laboratorio anterior sobre el folium:

[Generando mapas con Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

## Tarea 1: Marcar todos los puntos de lanzamiento en un mapa

Primero, intentemos agregar la ubicación de cada sitio en un mapa utilizando las coordenadas de latitud y longitud del sitio.

El siguiente conjunto de datos, denominado `spacex_launch_geo.csv`, es un conjunto de datos ampliado al que se le han añadido la latitud y la longitud para cada ubicación.

In [37]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Ahora puedes consultar las coordenadas de cada sitio.

In [38]:
# Seleccione las subcolumnas relevantes `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Las coordenadas anteriores son simplemente números que no ofrecen ninguna información intuitiva sobre la ubicación de los puntos de lanzamiento. Si tienes buenos conocimientos de geografía, puedes interpretarlos mentalmente. Si no, no hay problema. Visualicemos esas ubicaciones marcándolas en un mapa.

Primero necesitamos crear un objeto `Map` de Folium, con una ubicación central inicial en el Centro Espacial Johnson de la NASA en Houston, Texas.

In [39]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

Podríamos usar `folium.Circle` para agregar un área circular resaltada con una etiqueta de texto en una coordenada específica. Por ejemplo,

In [40]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

# Se modifica para que no de error de que no hay atribuido la definición para DivIcon, se importa  from folium.features import DivIcon

Deberías encontrar un pequeño círculo amarillo cerca de la ciudad de Houston y puedes hacer zoom para ver un círculo más grande.

Ahora, agreguemos un círculo para cada sitio de lanzamiento en el marco de datos `launch_sites`.

*TODO:*  Crea y añade `folium.Circle` y `folium.Marker` para cada sitio de lanzamiento en el mapa del sitio.

Un ejemplo de folium. Círculo:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

Un ejemplo de folium.Marcador:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [41]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

El mapa generado con los puntos de lanzamiento marcados debería tener un aspecto similar al siguiente:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Ahora, puedes explorar el mapa acercando o alejando las áreas marcadas

e intentar responder las siguientes preguntas:

* ¿Están todos los puntos de lanzamiento cerca de la línea del ecuador?

* ¿Están todos los puntos de lanzamiento muy cerca de la costa?

Además, intenta explicar tus conclusiones.

# Task 2: Marca en el mapa los lanzamientos exitosos/fallidos para cada sitio.

A continuación, intentemos mejorar el mapa añadiendo los resultados de los lanzamientos para cada sitio y veamos qué sitios tienen altas tasas de éxito.

Recordemos que el marco de datos `spacex_df` contiene registros detallados de los lanzamientos, y la columna `class` indica si el lanzamiento fue exitoso o no.

In [43]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [44]:
marker_cluster = MarkerCluster()

*TODO:* Crea una nueva columna en el dataframe `spacex_df` llamada `marker_color` para almacenar los colores de los marcadores según el valor de `class`.

In [45]:

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

*TODO:* Para cada resultado del lanzamiento en `spacex_df` data frame, añadir a `folium.Marker` para `marker_cluster`

In [46]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    # marker = folium.Marker(...)
    marker_cluster.add_child(marker)

site_map

Es posible que el mapa actualizado tenga un aspecto similar al de las siguientes capturas de pantalla:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

A partir de los marcadores etiquetados por colores en los grupos de marcadores, debería poder identificar fácilmente qué sitios de lanzamiento tienen tasas de éxito relativamente altas.

# TAREA 3: Calcular las distancias entre un sitio de lanzamiento y sus proximidades

Next, we need to explore and analyze the proximities of launch sites.

Primero, agreguemos una propiedad `MousePosition` al mapa para obtener las coordenadas de la posición del cursor sobre un punto. De esta manera, mientras exploras el mapa, podrás encontrar fácilmente las coordenadas de cualquier punto de interés (como una vía férrea).

In [47]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Ahora, acerca la imagen a un punto de lanzamiento y explora sus alrededores para ver si puedes encontrar fácilmente alguna vía férrea, carretera, línea costera, etc. Mueve el ratón a estos puntos y anota sus coordenadas (que se muestran en la parte superior izquierda) para calcular la distancia al punto de lanzamiento.

Ahora, acerca la imagen a un punto de lanzamiento y explora sus alrededores para ver si puedes encontrar fácilmente alguna vía férrea, carretera, línea costera, etc. Mueve el ratón a estos puntos y anota sus coordenadas (que se muestran en la parte superior izquierda) para calcular la distancia al punto de lanzamiento.

In [48]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*PENDIENTE:* Marcar un punto en la costa más cercana usando MousePosition y calcular la distancia entre el punto de la costa y el lugar de lanzamiento.

In [49]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

In [54]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
distance_marker = folium.Marker(
    coordinate,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
        )
    )

<class 'NameError'>: name 'coordinate' is not defined

*TODO:* Dibuja una polilínea entre un punto de lanzamiento y el punto de la costa seleccionado.

In [53]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

<class 'NameError'>: name 'coordinates' is not defined

Tu mapa actualizado con la línea de distancia debería verse como en la siguiente captura de pantalla:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* De forma similar, puedes trazar una línea entre un punto de lanzamiento y la ciudad, vía férrea, autopista, etc., más cercana. Para ello, primero debes usar la función "Posición del ratón" para encontrar sus coordenadas en el mapa.

Un símbolo en un mapa ferroviario podría tener este aspecto:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

Un símbolo en un mapa de carreteras podría verse así:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

Un símbolo de mapa de la ciudad podría verse así:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [52]:
# Crea un marcador con la distancia a la ciudad, vía férrea, autopista, etc. más cercana.
# Dibuja una línea desde el marcador hasta el punto de lanzamiento.

Tras trazar las líneas de distancia a las proximidades, podrá responder fácilmente a las siguientes preguntas:

* ¿Están las plataformas de lanzamiento cerca de las vías férreas?

* ¿Están las plataformas de lanzamiento cerca de las autopistas?

* ¿Están las plataformas de lanzamiento cerca de la costa?

* ¿Se mantienen las plataformas de lanzamiento a cierta distancia de las ciudades?

Además, por favor, explique sus conclusiones.

# Próximos pasos:

Ahora que has descubierto información muy interesante sobre la ubicación de los sitios de lanzamiento usando Folium, de forma muy interactiva, deberás crear un panel de control con Ploty Dash a partir de los registros detallados de los lanzamientos.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>